"""
Django settings for ezybaasmain project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import environ
import dj_database_url

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

env = environ.Env(DEBUG=(bool, False))
env_file = os.path.join(BASE_DIR, ".env")
environ.Env.read_env(env_file)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str('SECRET_KEY', default='xe*ndcprlhfn@y=t-(j1vk65r)uwhk97$h*_cyzxlqx+=g-t&y')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=('*','123'))

print('DEBUG='+str(DEBUG))
if DEBUG:
	#print('SECRET_KEY='+str(SECRET_KEY))
	print('SECRET_KEY='+str(SECRET_KEY))
	print('ALLOWED_HOSTS='+str(ALLOWED_HOSTS))


# This is DRF Rendering of the APIs
# This is not required as we used view based definition for each app
# ASPER - https://stackoverflow.com/questions/11898065/how-to-disable-admin-style-browsable-interface-of-django-rest-framework
# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework.authentication.SessionAuthentication',
#         'rest_framework.authentication.TokenAuthentication',
#         'rest_framework.authentication.BasicAuthentication',
#     ),
#     'DEFAULT_PERMISSION_CLASSES': (
#         'rest_framework.permissions.IsAuthenticated',
#     ),
# 	  'DEFAULT_RENDERER_CLASSES': (
#         'rest_framework.renderers.JSONRenderer',
#     )
# }

# 'rest_framework.renderers.BrowsableAPIRenderer'

# Application definition
INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'rest_framework',
	'rest_framework.authtoken',
	'rest_framework_swagger',
	'ezybaas',
	]


SWAGGER_SETTINGS = {
	'SHOW_REQUEST_HEADERS': True,
}

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ezybaasmain.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [
			# ADD YOUR DIRECTORY HERE LIKE SO:
			#
			#  BASE_DIR + '/templates/',
		],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	}
]


WSGI_APPLICATION = 'ezybaasmain.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
EZYBAAS_DEFAULT_DB = env.str('EZYBAAS_DB', default=('sqlite:///' + os.path.join(BASE_DIR, 'ezybaas.db')))

EZYBAAS_DB_CONN_MAX_AGE = env.int('EZYBAAS_DB_CONN_MAX_AGE', default=0) 
if EZYBAAS_DB_CONN_MAX_AGE < 0:
	EZYBAAS_DB_CONN_MAX_AGE = None 

DATABASES =  {
	'default': dj_database_url.config(	env = EZYBAAS_DEFAULT_DB,
                                    	default = EZYBAAS_DEFAULT_DB,
                                        conn_max_age = EZYBAAS_DB_CONN_MAX_AGE)
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOGIN_URL = 'login/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

# from ezybaas.db import *
# DATABASES['ezybaas']=EZYBAAS_DATABASES['ezybaas']
# DATABASE_ROUTERS = ['ezybaas.db.EzyBaasDbRouter']

# DATABASES['default']=EZYBAAS_DATABASES['test']

#INSTALLED_APPS += ['demo']   # WARNING: Added by EzyBaas. Please Do Not Remove.
INSTALLED_APPS += ['demo']   # WARNING: Added by EzyBaas. Please Do Not Remove.