#--------------------WARNING--------------------
#This File has been Generated by EzyBaaS. To make any changes, Use EzyBaaS Interface Only.
#Do NOT make any changes to this file Directly, EzyBaaS is not resposible for any loss of data.

from rest_framework import serializers
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated
from .models import ToDo

class ToDoSerializer(serializers.ModelSerializer):
	class Meta:
		model = ToDo
		fields = '__all__'

class ToDoViewSet(viewsets.ModelViewSet):
	permission_classes = (IsAuthenticated,)
	serializer_class = ToDoSerializer

	def get_queryset(self):
		queryset = []
		if self.request.user.has_perm('demo.delete_todo') and self.request.user.has_perm('demo.view_todo'):
			if self.request.user.has_perm('demo.change_todo') and self.request.user.has_perm('demo.add_todo'):
				queryset = ToDo.objects.all()
		return queryset


