#--------------------WARNING--------------------
#This File has been Generated by EzyBaaS. To make any changes, Use EzyBaaS Interface Only.
#Do NOT make any changes to this file Directly, EzyBaaS is not resposible for any loss of data.

from django.db import models


class ToDo(models.Model):
	status = models.CharField(max_length=255, unique=False, blank = True, null = True)
	item = models.CharField(max_length=255, unique=False, blank = True, null = True)
