#--------------------WARNING--------------------
#This File has been Generated by EzyBaaS. To make any changes, Use EzyBaaS Interface Only.
#Do NOT make any changes to this file Directly, EzyBaaS is not resposible for any loss of data.

from . import api
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'todo', api.ToDoViewSet, base_name='todo')

urlpatterns = router.urls
